# Generated by Django 2.2.4 on 2019-08-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190818_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insta_handle',
            field=models.URLField(max_length=70),
        ),
    ]
