# Generated by Django 2.2.4 on 2019-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='date',
        ),
        migrations.AddField(
            model_name='reserve',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
