# Generated by Django 2.2.4 on 2019-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20190819_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
